---
- hosts: localhost
  become: true
  vars:
    cloud: aws
    domainname: sentinel.cqsec.net
  roles:
    - tools
    - docker
    - minikube
    - operators
    - sentinel
    - dashboards
    - firefly
