---
- hosts: localhost
  become: true
  vars:
    domainname: sentinel.cqsec.net
    registry_host:
      auths:
        registry.gitlab.com:
          username: adriansteer
          password: glpat-xqx7_2ci27KyJFeCfQ9u
          auth: YWRyaWFuc3RlZXI6Z2xwYXQteHF4N18yY2kyN0t5SkZlQ2ZROXUK
  roles:
    - tools
    - docker
    - minikube
