---
- hosts: localhost
  become: true
  vars:
    domainname: sentinel.cqsec.net
    registry_host: registry.gitlab.com
    registry_user: adriansteer
    registry_pass: glpat-xqx7_2ci27KyJFeCfQ9u
  roles:
    - tools
    - docker
    - minikube
    - operators
    - sentinel
