---
- name: Firefly | Copy utilities
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - firefly-api-spec.py
    - keycloak_client.py
- name: Firefly | Infra | Clone repo
  ansible.builtin.git:
    repo: "https://{{ aws_instance_tags.tags.registry_user | b64decode | trim }}:{{ aws_instance_tags.tags.registry_pass | b64decode | trim }}@gitlab.com/cequence/research/third-party/firefly-iii.git"
    dest: /tmp/firefly-iii
- name: Firefly | Infra | Create namespace
  kubernetes.core.k8s:
    name: firefly
    api_version: v1
    kind: Namespace
    state: present
- name: Firefly | Infra | Create registry credentials
  shell:
    "kubectl create secret docker-registry regcred \
    --docker-server={{ aws_instance_tags.tags.registry_host | b64decode | trim }} \
    --docker-username={{ aws_instance_tags.tags.registry_user | b64decode | trim }} \
    --docker-password={{ aws_instance_tags.tags.registry_pass | b64decode | trim }} \
    --namespace=firefly"
- name: Firefly | Helm | Install release
  kubernetes.core.helm:
    name: firefly
    chart_ref: /tmp/firefly-iii/helm-chart/firefly-iii
    release_namespace: firefly
    values:
      imagePullSecrets:
        - name: regcred
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: "firefly.{{ domainname }}"
            paths:
              - path: /
                backend:
                  serviceName: firefly-iii
                  servicePort: 80
- name: Firefly | Infra | Local hosts entries
  lineinfile:
    name: /etc/hosts
    regexp: "^.* firefly.{{ domainname }}$"
    line: "{{ minikube_ip.stdout }} firefly.{{ domainname }}"
- name: Firefly | Infra | Create api user
  shell:
    "/usr/local/bin/keycloak_client.py --clientname api --create --admin"
  register: token
- name: Firefly | Infra | Upload spec
  shell:
    "/usr/local/bin/firefly-api-spec.py \
    --servername firefly.{{ domainname }} \
    --secret {{ token.stdout }} \
    --sentinel sentinel.{{ domainname }}"